### ISSUE TITLE
IP Blocked for STMP Validation

### ISSUE THREAD

**Issue by mhtngo** [truemail-rb/truemail#101]
### New Issue Checklist

- [x] I have updated truemail to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [ ] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [ ] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Issue Description

General question - hosting this AWS/EC2 - some domains block my IP for SMTP validation type. For example Outlook.com

What is general best practice to host truemail to prevent these blocked IP SMTP verification issues?

##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by bestwebua** [comment]
Hi, @mhtngo Thx for your question. Please check your [verifier host preconditions](https://truemail-rb.org/truemail-gem/#/quick-start?id=verifier-host-preconditions) first. Also I think that more flexible solution is to [use Truemail outside of your application](https://github.com/truemail-rb/truemail-rack-docker-image). For this case you can move out your Truemail instance to another cloud provider or even bare metal with white ip address. Anyway, ask the questions and I'll try to help you.
