### ISSUE TITLE
Are configurable timeouts specified on seconds or milliseconds?

### ISSUE THREAD

**Issue by wikiti** [truemail-rb/truemail#103]
### New Issue Checklist

- [x] I have updated truemail to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Issue Description

The documentation states the following for `connection_timeout ` and `response_timeout ` configuration options:

> Optional parameter. Connection timeout is equal to 2 **ms** by default.
> Optional parameter. A SMTP server response timeout is equal to 2 **ms** by default.

I understand that timeouts are specified in **milliseconds**. However, after taking a look at the source code, it seems to me that [Timeout.timeout](https://ruby-doc.org/stdlib-2.5.1/libdoc/timeout/rdoc/Timeout.html#method-c-timeout) is used to handle timeouts, which uses **seconds**.

Is the documentation wrong, or should timeouts be handled on milliseconds rather than seconds?

##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by bestwebua** [comment]
Hola, @wikiti! First of all I want to say thank you for your report. You're absolutely right! In point of fact `Timeout.timeout`, `Net::SMTP#open_timeout`, `Net::SMTP#read_timeout` use seconds, so `Truemail` uses seconds too. And this time there're wrong time units for configuration timeouts in readme and project docs. I will fix it today.

**Comment by bestwebua** [comment]
Fixed in [readme](https://github.com/truemail-rb/truemail/blob/master/README.md) and [docs](https://truemail-rb.org/truemail-gem/#/configuration?id=global-configuration).
