### ISSUE TITLE
[QUESTION] I don't understand the documentation

### ISSUE THREAD

**Issue by deploy595** [truemail-rb/truemail#113]
Please, can someone clarify these meanings:

* `real existence` - what does it mean exactly?
* `current email server` - I don't understand, what is `current` ?

https://github.com/truemail-rb/truemail#smtp-validation

![Screenshot_20201124_105128](https://user-images.githubusercontent.com/68423485/100069167-7841ca80-2e49-11eb-96b7-96d63ed9a60c.png)

**Comment by bestwebua** [comment]
Hello, @deploy595!
1. `real existence` in context of `user@domain.org` means that user `user` is exists on mx server of `domain.org`
2. `current email server` means extracted mail server during smtp validatioin session will become a target (current) mail server
