### ISSUE TITLE
[QUESTION] Verifier domain should refer to verefier host IP address?

### ISSUE THREAD

**Issue by eni9889** [truemail-rb/truemail#115]
### Question

Hi guys, thank you for this great gem. 

I was reading through the documentation and saw "Verifier domain should refer to verifier host IP address" can you please elaborate on this? Does this mean we need a root A record on the domain to point to ip address? Or is this something else?

Also, what about subdomains:
I.e a.mail.com, b.mail.com can each point to separate IP addresses with different emails and be used for verification without causing the whole domain to be blacklisted if one get's blacklisted?

**Comment by bestwebua** [comment]
You're welcome, @eni9889! Yes it's means that verifier domain (or subdomain) should have A record with ip-address the same as on host which truemail runs. You should follow this rule for the best email SMTP validation outcome. About your question about subdomains, it depends on blacklist configuration policy of host which will accept your smtp reqquest. Cheers!

**Comment by eni9889** [comment]
@bestwebua done :) also any recommendations for cloud providers that have port 25 open to set up the verifier on or does having a fully functional mail server not matter?

**Comment by bestwebua** [comment]
Yup, @eni9889! To have an MX records with a real mail server for verifier domain with existent verifier email should provide great result.
