### ISSUE TITLE
[BUG] SMTP debug shows errors but email still shows valid

### ISSUE THREAD

**Issue by eni9889** [truemail-rb/truemail#117]
I am trying to verify the following email which should be invalid:

```
carrieam70@hornail.com
```

I am getting this response:

```
{
    "date": "2020-12-02 14:47:25 +0000",
    "email": "carrieam70@hornail.com",
    "validation_type": "smtp",
    "success": true,
    "errors": null,
    "smtp_debug": [
        {
            "mail_host": "40.76.4.15",
            "port_opened": false,
            "connection": null,
            "errors": {}
        }
    ],
    "configuration": {
        "validation_type_by_domain": null,
        "whitelist_validation": false,
        "whitelisted_domains": null,
        "blacklisted_domains": null,
        "not_rfc_mx_lookup_flow": false,
        "smtp_safe_check": true,
        "email_pattern": "default gem value",
        "smtp_error_body_pattern": "default gem value"
    }
}
```

As a reference, this project shows the email as unreachable: https://github.com/amaurymartiny/check-if-email-exists

**Comment by bestwebua** [comment]
Hi, @eni9889! It happened because you have used smtp safe check feature.

> This option will be parse bodies of SMTP errors. It will be helpful if SMTP server does not return an exact answer that the email does not exist.

https://truemail-rb.org/truemail-gem/#/validations-layers?id=smtp-safe-check-enabled
