### ISSUE TITLE
[BUG] Every yahoo email shows as valid

### ISSUE THREAD

**Issue by eni9889** [truemail-rb/truemail#118]
### New bug checklist

- [x] I have updated `truemail` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Bug description
Any yahoo email I check shows up as valid. For example 7bzfv85getbay4f@yahoo.com

##### Complete output when running truemail, including the stack trace and command used

```
{
    "date": "2020-12-02 16:16:36 +0000",
    "email": "7bzfv85getbay4f@yahoo.com",
    "validation_type": "smtp",
    "success": true,
    "errors": null,
    "smtp_debug": null,
    "configuration": {
        "validation_type_by_domain": null,
        "whitelist_validation": false,
        "whitelisted_domains": null,
        "blacklisted_domains": null,
        "not_rfc_mx_lookup_flow": false,
        "smtp_safe_check": true,
        "email_pattern": "default gem value",
        "smtp_error_body_pattern": "default gem value"
    }
}
```

**Comment by bestwebua** [comment]
It's not truemail bug. It depends on smtp response status. Yahoo returns 250 status for all emails.

```bash
#<Net::SMTP::Response:0x00007f85e1579400 @status="250", @string="250 sender <verifier_email@domain.com> ok\n">
#<Net::SMTP::Response:0x00007f85e1579040 @status="250", @string="250 recipient <7bzfv85getbay4f@yahoo.com> ok\n">
```

**Comment by eni9889** [comment]
@bestwebua any chance you can implement this for yahoo and aol emails? https://github.com/amaurymartiny/check-if-email-exists/blob/master/core/src/smtp/yahoo.rs

**Comment by bestwebua** [comment]
@eni9889 Looks like additional validation layer for predefined email provider list. But it depends on frontend implementation of different mail providers. Honestly, I don't know, is it a good idea.

**Comment by eni9889** [comment]
@bestwebua I believe it is the only way to validate yahoo and aol emails otherwise for yahoo and Aol the gem doesn't work at all. It could be made an option for users to enable/disable but personally I think without it it just means I'd have to use custom code for those two providers.

**Comment by bestwebua** [comment]
@eni9889 So what you propose for cases with another mail providers with the same case of rcptto response as yahoo & aol? Go to producing different implementation for each ones?

**Comment by eni9889** [comment]
@bestwebua I suppose so. The alternative is not being able to validate a large portion of emails. In my case, this is about 10-15% of emails

**Comment by bestwebua** [comment]
By the way `truemail` is not for bulk validations. Maybe additional layer with configurable by user scenarios composed on mail provider frontend behaviour will make sence.

**Comment by eni9889** [comment]
@bestwebua I am using it as a validation service when collecting user emails using pop-ups on my site. So not for cleaning bulk lists. I'd be happy to make a PR for the AOL/Yahoo emails, but it would be useful to have an interface for such a thing.

**Comment by bestwebua** [comment]
@eni9889 Yay, let's returns for this discussion after new year, okay? :)

**Comment by eni9889** [comment]
@bestwebua sounds good :) happy holidays

**Comment by jhemarcos** [comment]
Hey! Shall we go back to this discussion? Do you have a plan @bestwebua? :)

**Comment by bestwebua** [comment]
Thinking about additional pluggable layer as independent gem. Next week I'm going to initialize repo for this one.

**Comment by muditjuneja** [comment]
Hey @bestwebua is this something that has been developed here now?

**Comment by bestwebua** [comment]
@muditjuneja Just in my todo list for now.

**Comment by etranger7** [comment]
Hi, why is this not an open issue? I understand this stems from Yahoo's response but the problem still exists.
