### ISSUE TITLE
[FEATURE] Your feature request title here

### ISSUE THREAD

**Issue by n-rodriguez** [truemail-rb/truemail#119]
### New feature request checklist

- [x] I have updated `truemail` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Feature description

It could be nice to have access to validator result object : https://github.com/truemail-rb/truemail/blob/master/lib/truemail/validator.rb#L8

So we can do 

```ruby
request = Truemail.validate(email)
if request.result.valid? # or request.result.success?
else
end
```

**Comment by n-rodriguez** [comment]
It's already the case (https://github.com/truemail-rb/truemail/blob/f4758cfd64ee2cad0324cb2ab8d53049d857c086/lib/truemail/executor.rb#L4). Maybe it should be added to the documentation.

**Comment by bestwebua** [comment]
@n-rodriguez `Truemail::Validator#result` is a public method.

https://www.rubydoc.info/gems/truemail/2.2.0/Truemail/Validator
> Attributes inherited from Executor #result

I'm going to add this mention in the docs next week.
