### ISSUE TITLE
[FEATURE] DNS resolver configuration

### ISSUE THREAD

**Issue by verdi8** [truemail-rb/truemail#126]
Hello,

In order to make Truemail work in some restricted environments (especially where the `/etc/resolv.conf` file cannot be modified), it would be great that the [Resolv::DNS.new](https://ruby-doc.org/stdlib-2.6.1/libdoc/resolv/rdoc/Resolv/DNS.html) configuration could be defined in the `Truemail.configuration` .

Eg:
```ruby
  # Optional parameter. This option defines how the domain names are resolved. 
  # See the Resolv::DNS.new documentation for further info.
  config.resolve_dns_config_info={ :nameserver => ['8.8.8.8', '8.8.4.4'] }
```
Thanks!

**Comment by bestwebua** [comment]
Hi, @verdi8! Thanks for your report. Honestly, I'm working on this feature. It will be able till the end of this month 😀

**Comment by verdi8** [comment]
Great and funny coincidence!
Looking forward to testing it. 😀

**Comment by bestwebua** [comment]
Feature is available in latest release. Have a great weekend ;)
