### ISSUE TITLE
[QUESTION] Is there a way to check for anonymous email addresses with truemail? 

### ISSUE THREAD

**Issue by etagwerker** [truemail-rb/truemail#128]
### New question checklist

- [X] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [X] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [X] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Question

Hi there, this gem looks really interesting and useful, thanks for open sourcing it! I was wondering if there is a way to check for anonymous email addresses? It might be useful for some projects to know whether someone is signing up with an email address created at an anonymous email provider (e.g. https://www.mailinator.com)

**Comment by bestwebua** [comment]
Hi, @etagwerker. Thanks for your question. It's pretty easy 😃 You should just define the list of unwanted domains in Truemail configuration:

```ruby
require 'truemail'

Truemail.configure do |config|
  config.blacklisted_domains = ['black-domain.com', 'somedomain.com']
end
```

It's responsibility of Truemail whitelist/blacklist validation layer. You can find more info in docs: https://truemail-rb.org/truemail-gem/#/validations-layers?id=whitelistblacklist-check Cheers!
