### ISSUE TITLE
[BUG] Default Regex Not Catching Previous Pattern

### ISSUE THREAD

**Issue by your-favorite-dev** [truemail-rb/truemail#181]
### New bug checklist

- [x] I have updated `truemail` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Bug description
I was using version 2.4.2 and the following would report as incorrect `in@correct@email.com `
I upgraded to the current version and now the same string will pass. 

##### Complete output when running truemail, including the stack trace and command used

<details>
### 2.4.2

<img width="839" alt="Screen Shot 2021-10-05 at 2 00 40 PM" src="https://user-images.githubusercontent.com/15678391/136078255-20e36559-a0a7-412c-98f0-fd1f248eaae9.png">

### Current

<img width="819" alt="Screen Shot 2021-10-05 at 2 03 11 PM" src="https://user-images.githubusercontent.com/15678391/136078293-a0bf8902-8179-4bff-97f4-7741e004fdd9.png">
</details

>

**Comment by bestwebua** [comment]
Hi, Andrew! Thanks for your bug report. This fix is available in latest (2.5.2) truemail release. Cheers!

<img width="487" alt="Screenshot 2021-10-06 at 12 37 13 PM" src="https://user-images.githubusercontent.com/14002692/136178455-58f5510f-d84c-4afa-a583-7a9d4598a983.png">
