### ISSUE TITLE
[BUG] SMTP Validation may fail from Ruby 3.0 onwards

### ISSUE THREAD

**Issue by esb** [truemail-rb/truemail#184]
### New bug checklist

- [X] I have updated `truemail` to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [X] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [X] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

[BUG] Ruby 3.0 changes the handling of SSL certificate verification which will cause failures when the certificate names don't match the IP addresses.

### Bug description
The interface for the Net::SMTP start method changed in 3.0 to 

```ruby
start(address, port = nil, helo: 'localhost', user: nil, secret: nil, authtype: nil, tls_verify: true, tls_hostname: nil) { |smtp| ... }
```

The old method continues to be supported, but it looks like they changed to enable tls_verify by default. Under the 2.7 library, there's no problem connecting to gmail.com, but from 3.0 you get a connection error stating that there's a certificate error.

My feeling is that SSL errors are irrelevant for email verification, so tls_verify should always be off, and a quick way to fix this is to add the tls_verify: false option to the SMTP start method, although you would need to check the library version and only do this for versions 3.0+.

**Comment by bestwebua** [comment]
@esb, this fix is available in latest (2.5.3) truemail release. Cheers!
