### ISSUE TITLE
Is there any way to detect catchAll?

### ISSUE THREAD

**Issue by salim-buet03** [truemail-rb/truemail#185]
Thanks for this amazing library.

I want to have some extra features just beside the delivery check.
is email id catchAll? 
is HostExists? 
is FullInbox? 

anyone can help pls?

**Comment by bestwebua** [comment]
Hello, @salim-buet03! The `HostExists` feature is already implemented: https://truemail-rb.org/truemail-gem/#/validations-layers?id=mx-validation. What you mean for: `is email id catchAll?`, `is FullInbox?`, could you provide more details?

**Comment by salim-buet03** [comment]
Great thanks for your response :) 
catchAll means, some email provider domain accepts all email address like @yahoo.com 
If you try to validate any_invalid_username@yahoo.com, still any verify system return success. Just becoz, it's catchAll (accept-all). By the way, I have already fixed catchAll just by validating any_invalid_username@emailDomain. If it returns success then, it's catchAll (Accepting all emails). 
idFullInbox : I found this return in some email validator system. It may be, email address inbox is full and not able to receive any more emails. Not sure how they do it. I am just trying to figure it out.

Thanks

**Comment by salim-buet03** [comment]
Solved isFullInbox, by the error message: "552-5.2.2 The email account that you tried to reach is over quota and inactive."

**Comment by bestwebua** [comment]
@salim-buet03 Thx for details. But I think that these features are outside of scope of this library (and email validations in general).

**Comment by salim-buet03** [comment]
you are right :) 
But catchAll is really important in terms of email validation. Almost every email validator website has this feature.

**Comment by bestwebua** [comment]
No problem to process emails from providers like yahoo by custom scenario. I repeat, this is not the responsibility of this library.
