### ISSUE TITLE
[QUESTION] Is there any way to dynamically require net-smtp for ruby 3?

### ISSUE THREAD

**Issue by allard** [truemail-rb/truemail#193]
I understand that a lot of classes net-smtp, digest, and others have been moved from builtin classes to gems in Ruby 3. As a result of that truemail now requires net-smtp as a dependency, which in turn requires digest as a dependency. So when loading truemail v2.6+ on an app that does not use ruby 3, there's now warnings during load because digest (that declares constants) is loaded twice, both from the digest gem and using the builtin class in ruby 2.

Ideally, net-smtp should only be a dependency of truemail when running ruby 3 but I'm not sure if it's possible to specify dependencies like that?

**Comment by bestwebua** [comment]
Hi, @allard! Could you provide your current env where deprecation warnings happens? I currently thinking about dirty fix like:

```ruby
spec.add_runtime_dependency 'net-smtp', '~> 0.3' if ::RUBY_VERSION >= '3.1.0'
```

And 3 different calls of `Net::SMTP` instance to avoid redefinig buildin implementations and warnings...

```ruby
class Session
  require 'net/smtp'

  UNDEFINED_VERSION = '0.0.0'

  def initialize(host, port, connection_timeout, response_timeout)
    @net_smtp_version = resolve_net_smtp_version
    @net_smtp = (old_net_smtp? ? ::Net::SMTP.new(host, port) : ::Net::SMTP.new(host, port, tls_verify: false)).tap do |settings|
      settings.open_timeout = connection_timeout
      settings.read_timeout = response_timeout
    end
  end

  def start(helo_domain, &block)
    return net_smtp.start(helo_domain, &block) if net_smtp_version < '0.2.0'
    return net_smtp.start(helo_domain, tls_verify: false, &block) if old_net_smtp?
    net_smtp.start(helo: helo_domain, &block)
  end

  private

  attr_reader :net_smtp_version, :net_smtp

  def resolve_net_smtp_version
    return ::Net::SMTP::VERSION if ::Net::SMTP.const_defined?(:VERSION)
    Truemail::Validate::Smtp::Request::Session::UNDEFINED_VERSION
  end

  def old_net_smtp?
    net_smtp_version < '0.3.0'
  end
end
```

**Comment by bestwebua** [comment]
@allard, I have released new `truemail` version (2.6.1) with this fix inside. Could you check out warnings behaviour now?

**Comment by allard** [comment]
Works perfectly @bestwebua, thank you.

**Comment by bestwebua** [comment]
@allard thanks are received in the form of repo stars 😇

**Comment by adzap** [comment]
I get warnings from `net-protocol` constants due to `net-smtp` being loaded in Ruby 2.7.5. Same basic issue so it seem the Ruby version guard is not working?

**Comment by bestwebua** [comment]
Hi, @adzap! On which `truemail` version it happens? It should be fixed on latest:

https://github.com/truemail-rb/truemail/blob/a1354eab1afc8cb62604ae3aab118c4a60924d1d/truemail.gemspec#L34

So on your current environment should be loaded out of the box `net-smtp` implementation. Maybe it causes due loading another gem? Need to investigate in your current case.

**Comment by adzap** [comment]
This was on v2.6.3 and where net-smtp was introduced. I'll double check my dependencies.

**Comment by bestwebua** [comment]
Thank you, Adam! Let me know your investigation details.

**Comment by adzap** [comment]
So the only gem with `net-smtp` and hence `net-protocol` gems is `truemail`. The warnings only started when going from `truemail` v2.6.2 to v2.6.3.

**Comment by bestwebua** [comment]
Thanks, @adzap! Good catch. Seems like RubyGems ignores version guard. Look into diff in `truemail.gemspec`: https://github.com/truemail-rb/truemail/compare/v2.6.2...v2.6.3 I'm going to try rollback to: `net-smtp ~> 0.3`.

**Comment by bestwebua** [comment]
Nope, it doesn't work. Looks like RubyGems checks `.ruby-version` before...

**Comment by bestwebua** [comment]
> Great, it works. Thanks! You had to drop net-smtp?
> […](#)
> On 9 Feb 2022, 10:47 PM +1100, Vladislav Trotsenko ***@***.***>, wrote: I did it! @adzap, please chekout on your current env — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Yup! Only for Rubies < 3.1 😜

**Comment by adzap** [comment]
How does it work? Just looking at the gemspec it seems you only changed the `net-smtp` tiny version. The `RUBY_VERSION` guard does work then?

I'm interested because I've seen other gem projects starting to uses these core gems and getting the same issues.

**Comment by bestwebua** [comment]
> How does it work? Just looking at the gemspec it seems you only changed the `net-smtp` tiny version. The `RUBY_VERSION` guard does work then?
> 
> I'm interested because I've seen other gem projects starting to uses these core gems and getting the same issues.

@adzap It's straight enough:

1. Specify Ruby version for RubyGems in `.ruby-version`, I think it should minimal version, specified in `spec.required_ruby_version`
2. Use version guard in `gemspec` for needed dependencies
3. Push your gem to RubyGems and checkout runtime/development dependencies sections

It works 💯
