### ISSUE TITLE
[ISSUE] Cleanup gemspec

### ISSUE THREAD

**Issue by n-rodriguez** [truemail-rb/truemail#215]
Hi there!

Since you require Ruby >= 2.5.0, I think you can replace this https://github.com/truemail-rb/truemail/blob/d6fcacda501cdb1206bbe8084e1f9d0e077384a8/truemail.gemspec#L3-L5 by 

```ruby
require_relative 'lib/truemail/version'
```

like https://github.com/mperham/sidekiq/blob/main/sidekiq.gemspec

Thanks for the great job!

**Comment by bestwebua** [comment]
@n-rodriguez Thank you, man! I have rescuing myself & family from Ukraine territory, I will update this one as soon as possible.
