### ISSUE TITLE
[QUESTION] My Config Returns 'false' for Truemail.valid?(my_email, with: :smtp) for Existing Email Addresses. How Do I Fix This?

### ISSUE THREAD

**Issue by lightbe** [truemail-rb/truemail#227]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Question

I have two personal email addresses that I'm using to test with. Here is my configuration in config/application.rb.
```
Truemail.configure do |config|
  config.verifier_email = 'contactus@mydomain.com'
  config.email_pattern = /my_regular_expression/
  config.connection_timeout = 1
  config.response_timeout = 1
  config.default_validation_type = :regex
  config.not_rfc_mx_lookup_flow = true
  config.logger = { tracking_event: :error, stdout: true, log_absolute_path: 'log/truemail.log' }
end
```
Here is my code.

`Truemail.valid?(my_email) returns true`

`Truemail.valid?(my_email, with: :mx) returns true`

`Truemail.valid?(my_email, with: :mx_blacklist) returns true`

```
Truemail.valid?(my_email, with: :smtp) returns the following in the log:

E, [2022-09-16T18:09:45.386459 #4046] ERROR -- : Truemail smtp validation for my_email failed (smtp: smtp error)

ATTEMPT #1:
mail host: host_1
port opened: false
connection: 
errors: 

ATTEMPT #2:
mail host: host_2
port opened: false
connection: 
errors: 

ATTEMPT #3:
mail host: host_3
port opened: false
connection: 
errors: 

ATTEMPT #4:
mail host: host_4
port opened: false
connection: 
errors: 

ATTEMPT #5:
mail host: host_5
port opened: false
connection: 
errors: 

CONFIGURATION SETTINGS:
whitelist validation: false
not rfc mx lookup flow: true
smtp fail fast: false
smtp safe check: false
email pattern: (?-mix:my_regular_expression
smtp error body pattern: default gem value
```
I didn't set smtp fail fast or smtp safe check to true because two email addresses that I know don't exist were returning that they were valid. I received AWS SES bounce emails for both of them. One email said the mailbox was unavailable and the other account said that the mailbox doesn't exist.

I don't know how to fix this so I can check if an email address exists.

**Comment by bestwebua** [comment]
Hi, @lightbe! Please look at log, port opened: false. Seems smtp port on your validation host is closed. You need to contact your service provider to open it. It's not a truemail issue. Cheers!

**Comment by lightbe** [comment]
The Truemail documentation doesn't clearly say that the SMTP port in the configuration section is from the validation host. It's not mentioned in the comments in the configuration sample either. Thanks for the clarification.

**Comment by lightbe** [comment]
@bestwebua thanks for the response. I set smtp_port in my configuration to the port I use to successfully send AWS SES emails from my Rails websites but I still see port opened: false in the log.

I checked the [Verifier host preconditions](https://truemail-rb.org/truemail-gem/#/quick-start?id=verifier-host-preconditions) again to see what was missing about the SMTP check. My domain is a GoDaddy domain. I had forgotten that now their domains have 2 A records. I can't add a PTR record anymore like I could before. Can I use this gem with a domain setup like this?

**Comment by bestwebua** [comment]
> @bestwebua thanks for the response. I set smtp_port in my configuration to the port I use to successfully send AWS SES emails from my Rails websites but I still see port opened: false in the log.

@lightbe It `smtp_port` should be `25`. It's option for edge case rather than for regular case. In 99% smtp port will be 25. Look here, the same issue as yours: https://github.com/truemail-rb/truemail-rack-docker-image/issues/19

> I checked the [Verifier host preconditions](https://truemail-rb.org/truemail-gem/#/quick-start?id=verifier-host-preconditions) again to see what was missing about the SMTP check. My domain is a GoDaddy domain. I had forgotten that now their domains have 2 A records. I can't add a PTR record anymore like I could before. Can I use this gem with a domain setup like this?

It's just for best validation outcome. You can use it without, but I don't know for how long it will work without ban from mail providers side. Just for test you can skip all these preconditions. And check your validation results for some existing google email as an example. It should work.

**Comment by lightbe** [comment]
@bestwebua I will ask AWS to remove the port 25 restriction and try again. I will post my results here. Thanks so much for this information as I have limited knowledge of what's under the hood regarding email processing.

**Comment by bestwebua** [comment]
You're welcome, @lightbe! The best appreciation is +1 star for the project 😄
