### ISSUE TITLE
[BUG] Email addresses with comma are valid

### ISSUE THREAD

**Issue by SofiaSousa** [truemail-rb/truemail#232]
### New bug checklist

- [x] I have updated `truemail` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

[BUG] Email addresses with comma are valid

### Bug description
Even though the default `email_pattern` doesn't allow commas (checked on [Rubular](https://rubular.com/)), Truemail is returning `true` when an email address like `sofia,sousa@example.com` is validated.

````
irb(main):001:0> Truemail::VERSION
=> "3.0.0"
irb(main):002:0> Truemail.validate('sofia,sousa@example.com', with: :regex)
=> 
#<Truemail::Validator:0x0000000116a600b0
 @result=
  #<struct Truemail::Validator::Result
   success=true,
   email="sofia,sousa@example.com",
   domain="example.com",
   mail_servers=[],
   errors={},
   smtp_debug=nil,
   configuration=
    #<Truemail::Configuration:0x0000000116a601f0
     @blacklisted_domains=[],
     @blacklisted_emails=[],
     @blacklisted_mx_ip_addresses=[],
     @connection_attempts=2,
     @connection_timeout=2,
     @default_validation_type=:smtp,
     @dns=[],
     @email_pattern=
      /(?=\A.{6,255}\z)(\A([\p{L}0-9]+[\w\p{L}.+!~,'&%#*^`{}|\-\/?=$]*)@((?i-mx:[\p{L}0-9]+([\-.]{1}[\p{L}0-9]+)*\.\p{L}{2,63}))\z)/,
     @logger=
      #<Truemail::Logger:0x0000000114ab0210
       @event=:error,
       @file="./log/truemail.log",
       @stdout=false>,
     @not_rfc_mx_lookup_flow=false,
     @response_timeout=2,
     @smtp_error_body_pattern=/(?=.*550)(?=.*(user|account|customer|mailbox)).*/i,
     @smtp_fail_fast=true,
     @smtp_port=25,
     @smtp_safe_check=true,
     @validation_type_by_domain={},
     @verifier_domain="example.com",
     @verifier_email="verifier@example.com",
     @whitelist_validation=false,
     @whitelisted_domains=[],
     @whitelisted_emails=[]>>,
 @validation_type=:regex>
```

**Comment by bestwebua** [comment]
Hi, @SofiaSousa! Thanks for your report. The local part can include a comma. This has been discussed here: https://github.com/truemail-rb/truemail/issues/159. It's an expected truemail behaviour as you can in test cases: https://github.com/truemail-rb/truemail/blob/master/spec/truemail/core_spec.rb#L40
