### ISSUE TITLE
[FEATURE] Using SMTP through SOCKS proxy

### ISSUE THREAD

**Issue by DZai** [truemail-rb/truemail#238]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Question

Great work!
Is there a way to use the smtp through a SOCKS proxy?
I checked the readme and issues and couldn't find a description of using a proxy, so if I missed it, please let me know

Thank you

**Comment by bestwebua** [comment]
Hello, @DZai! Thanks for you question. For this time there is no availability to configure `truemail` to use SMTP throught SOCKS proxy.

**Comment by DZai** [comment]
> 
SOCKS5. Will it be supported in the future?

**Comment by bestwebua** [comment]
@DZai I'll add it to my roadmap.

**Comment by Nyceane** [comment]
any update on this?

**Comment by bestwebua** [comment]
Seems like this feature on freeze.

**Comment by h3110Fr13nd** [comment]
Any update or workaround?
