### ISSUE TITLE
[QUESTION] how do we validate addresses containing a plus sign?

### ISSUE THREAD

**Issue by georgeglarson** [truemail-rb/truemail#243]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Question 
how can we validate emails containing plus signs?

email addresses with a plus sign are failing validation.  the API seems to be converting them to a space

thanks!

```
❯ curl -sS -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: TOPSECRET" http://truemail.example.com:9292\?email\=help+me@example.com 

{
  "date": "2022-12-23 12:08:26 +0000",
  "email": "help me@example.com",
  "validation_type": "regex",
  "success": false,
  "errors": {
    "regex": "email does not match the regular expression"
  },
```

**Comment by bestwebua** [comment]
@georgeglarson Hi! Your question out of scope of truemail gem. Please use right place. To interact with truemail server you can use `truemail-client`. Otherwise you should encode reserved chars directly, for your case it is `%2b`

**Comment by georgeglarson** [comment]
thanks for the answer!  

i did make an honest effort to choose the right place and, ultimately, chose the one labeled only 'truemail' instead of, ostensibly, something more specific.   the distinctions might not be so clear to a newcomer as they might seem to you.  
again, i definitely appreciate your rapid help
