### ISSUE TITLE
[BUG] Email addresses with multiple dashes are not allowed

### ISSUE THREAD

**Issue by Sybe** [truemail-rb/truemail#263]
### New bug checklist

- [x] I have updated `truemail` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

### Bug description

Email addresses with multiple consecutive dashes in the domain part are not allowed by the regex. For example `info@truemail---website.com`. According to rfc1035 a domain with multiple dashes is allowed though
##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre>Truemail::RegexConstant::REGEX_DOMAIN_PATTERN.match?("truemail---website.com")</pre>
</details>

**Comment by bestwebua** [comment]
Hi, @Sybe! Thanks for your report. This fix is already in a new release. Cheers!
