### ISSUE TITLE
[QUESTION] i need a tutorial for a nood to run this on raspberry pi

### ISSUE THREAD

**Issue by enzoibanez** [truemail-rb/truemail#264]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-gem)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail/issues)

**Comment by enzoibanez** [comment]
I apologize, but I was unable to get the truemail program to work. I must admit that my skills are limited, but I sought help on chatgpt and Bing chat in an attempt to make it function, but I didn't achieve any results. I was wondering if there is any tutorial that could assist me? I haven't found anything, and chatgpt hasn't solved the mystery of getting it to work.

**Comment by enzoibanez** [comment]
no one can help me?

**Comment by bestwebua** [comment]
@enzoibanez Hello! I didn't run `truemail` on raspberry pi. And I have no capacity to figure out with this question.

**Comment by bestwebua** [comment]
@enzoibanez All `truemail` documentation you can find here: https://truemail-rb.org/
