### ISSUE TITLE
[ISSUE] Using an instance instead of a class in event logger configuration

### ISSUE THREAD

**Issue by n-rodriguez** [truemail-rb/truemail#291]
Hi there!

I'm testing the new `logger` feature and found some bugs around it :

1. it should accept an instance of logger and not a class

Providing a class means that you (`truemail`) are in charge of configuring the logger which is IMHO not your responsability. You should use the logger instance as is, if provided. For example I use [logging](https://github.com/TwP/logging) to manage logs in my Rails app and thus I already have instances of logger configured and ready to use (by me or a gem). Those loggers are instance object and not `class`, thus I get this error :

```sh
/Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/ruby/3.2.0/gems/truemail-3.2.0/lib/truemail/configuration.rb:128:in `raise_unless': #<Logging::Logger:0x00000001132ad938> is not a valid logger= (Truemail::ArgumentError)
```

2. in the case where the user passes its own logger, `stdout` and `log_absolute_path` should not be mandatory.

For the same reason as above. In my case `logging` provides appenders for logger instances like `$stdout` or `files` and everything is already configured to work in `dev` / `ci` environments (local, log to `$stdout` and `file`) and `staging` / `production` environments (docker, log to `$stdout` only).

It also handles logs format (colored text in `dev` / `ci`, json in `staging` / `production` ), tags, etc..

Not being able to reuse this is a pity 😢 

3. if the user don't use the `logger_class` option and use the `truemail` logger, it should be instantiated once and not on each call to logger :

https://github.com/truemail-rb/truemail/blob/ec7a9d0c175dd66b10b75fa6e89fe3d8715a9946/lib/truemail/logger.rb#L32

Thank you!

**Comment by bestwebua** [comment]
Thanks, @n-rodriguez! I had same ideas yesterday, after release 🫣😀 Agree. I'm gonna update current logger feature implementation in a few days.

**Comment by bestwebua** [comment]
Done.
